// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using livrasonAPP.API.Data;

#nullable disable

namespace livrasonAPP.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230421010230_DbCr")]
    partial class DbCr
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("livrasonAPP.API.Models.Coli", b =>
                {
                    b.Property<int>("ColiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientAdress")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientTele")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientVille")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateLivraison")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateRamassage")
                        .HasColumnType("TEXT");

                    b.Property<int>("Montant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SituationColi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ColiId");

                    b.HasIndex("UserId");

                    b.ToTable("Colis");
                });

            modelBuilder.Entity("livrasonAPP.API.Models.Reclamation", b =>
                {
                    b.Property<int>("ReclamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateRecl")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessRecl")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepenseRecl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Situation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitreRecl")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReclamId");

                    b.HasIndex("UserId");

                    b.ToTable("Reclamations");
                });

            modelBuilder.Entity("livrasonApp.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CinUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("RipUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("livrasonAPP.API.Models.Coli", b =>
                {
                    b.HasOne("livrasonApp.API.Models.User", null)
                        .WithMany("Colis")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("livrasonAPP.API.Models.Reclamation", b =>
                {
                    b.HasOne("livrasonApp.API.Models.User", "User")
                        .WithMany("Reclamations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("livrasonApp.API.Models.User", b =>
                {
                    b.Navigation("Colis");

                    b.Navigation("Reclamations");
                });
#pragma warning restore 612, 618
        }
    }
}
